# Site wide configuration

title:            The Flying One
locale:           en_US
url:              http://theflyingone.com


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Site owner
owner:
  name: Amy
  avatar: avatar.jpg
  bio: "freelance front-end web dev, podcastaholic & admitted wow player - creator of Bermuda Mapp  - equal parts candid and snarky ;)"
  email: amy@amypeniston.com
  disqus-shortname:
  twitter: amypeniston
  facebook: 
  google:
    plus: 
    analytics: UA-37249439-1
    verify: 
    ad-client:
    ad-slot:
  bing-verify:
  github: amypeniston
  stackoverflow: #username
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
